version: '3'
networks:
  atelier.net:
    driver: bridge

# ===============================
#     Docker for API Slim
# ===============================
services:
  api:
    image: 'canals/php:latest'
    environment:
      - VHOST_HOSTNAME=api.atelier.local
      - VHOST_DOCROOT=/var/www/public
    ports:
      - '8000:80'
      - '8043:443'
    volumes:
      - './api:/var/www/'
    working_dir: /var/www/
    networks:
      atelier.net:
        aliases:
          - api.atelier.local
  api.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    environment:
      - MYSQL_ROOT_PASSWORD=atelier
      - MYSQL_USER=atelier
      - MYSQL_PASSWORD=atelier
      - MYSQL_DATABASE=atelier
    ports:
      - '3307:3306'
    networks:
      - atelier.net
    volumes:
      - './api/sql:/var/sql'

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - atelier.net
