-- MySQL Script generated by MySQL Workbench
-- Mon Mar 27 16:02:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tedyspo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tedyspo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tedyspo` DEFAULT CHARACTER SET utf8 ;
USE `tedyspo`;

-- -----------------------------------------------------
-- Table `tedyspo`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tedyspo`.`event` (
  `id_event` VARCHAR(36) NOT NULL,
  `title` VARCHAR(80) NOT NULL,
  `description` LONGTEXT NULL,
  `date` TIMESTAMP NOT NULL,
  `is_public` TINYINT NULL,
  PRIMARY KEY (`id_event`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auth`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tedyspo`.`user` (
  `id_user` VARCHAR(36) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(30) NULL,
  `firstname` VARCHAR(30) NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `mail_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tedyspo`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tedyspo`.`comment` (
  `id_comment` INT NOT NULL AUTO_INCREMENT,
  `comment` LONGTEXT NULL,
  `id_event` VARCHAR(36) NULL,
  `id_user` VARCHAR(36) NULL,
  PRIMARY KEY (`id_comment`),
  INDEX `id_evenement_idx` (`id_event` ASC) VISIBLE,
  INDEX `id_utilisateur_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `comment_event`
    FOREIGN KEY (`id_event`)
    REFERENCES `tedyspo`.`event` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comment_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `tedyspo`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tedyspo`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tedyspo`.`location` (
  `id_location` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL,
  `lat` DECIMAL(65) NULL,
  `long` DECIMAL(65) NULL,
  `is_related` TINYINT NULL,
  `id_event` VARCHAR(45) NULL,
  PRIMARY KEY (`id_location`),
  INDEX `id_evenement_idx` (`id_event` ASC) VISIBLE,
  CONSTRAINT `location_event`
    FOREIGN KEY (`id_event`)
    REFERENCES `tedyspo`.`event` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tedyspo`.`link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tedyspo`.`link` (
  `id_link` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(80) NULL,
  `link` VARCHAR(750) NULL,
  `id_event` VARCHAR(36) NULL,
  PRIMARY KEY (`id_link`),
  INDEX `id_evenement_idx` (`id_event` ASC) VISIBLE,
  CONSTRAINT `link_event`
    FOREIGN KEY (`id_event`)
    REFERENCES `tedyspo`.`event` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tedyspo`.`event_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tedyspo`.`event_user` (
  `state` VARCHAR(16) NOT NULL,
  `comment` LONGTEXT NULL,
  `id_event` VARCHAR(36) NULL,
  `id_user` VARCHAR(36) NULL,
  INDEX `id_event_idx` (`id_event` ASC) VISIBLE,
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `user_event`
    FOREIGN KEY (`id_event`)
    REFERENCES `tedyspo`.`event` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `event_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `tedyspo`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tedyspo`.`event_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tedyspo`.`event_event` (
  `title` VARCHAR(80) NULL,
  `id_main_event` VARCHAR(36) NULL,
  `id_additional_event` VARCHAR(36) NULL,
  INDEX `id_main_event_idx` (`id_main_event` ASC) VISIBLE,
  INDEX `id_additional_event_idx` (`id_additional_event` ASC) VISIBLE,
  CONSTRAINT `event_main_event`
    FOREIGN KEY (`id_main_event`)
    REFERENCES `tedyspo`.`event` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `event_additional_event`
    FOREIGN KEY (`id_additional_event`)
    REFERENCES `tedyspo`.`event` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tedyspo`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tedyspo`.`media` (
  `id_media` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(500) NULL,
  `type` VARCHAR(10) NULL,
  `id_comment` INT NULL,
  PRIMARY KEY (`id_media`),
  INDEX `id_comment_idx` (`id_comment` ASC) VISIBLE,
  CONSTRAINT `event_comment`
    FOREIGN KEY (`id_comment`)
    REFERENCES `tedyspo`.`comment` (`id_comment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
